services:
  db:
    image: mariadb:10.4
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - pma
      - default

  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/app
    working_dir: /app
    
  redis:
    image: redis:7

  node:
    image: node:23
    ports:
      - "3000:3000"
    volumes:
      - ./assets/react/:/app
    working_dir: /app/build
    command: sh -c "npm i && npm run watch"

  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost:8000
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    volumes:
      - mercure_data:/data
      - mercure_config:/config

networks:
  pma:
    external: true

volumes:
  db_data:
  mercure_data:
  mercure_config:
