services:
  db:
    image: mariadb:11.8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - default

  php:
    build:
      context: .
      dockerfile: .devops/docker/Dockerfile
      target: ${BUILD_TARGET:-dev}
    image: ghcr.io/fan2shrek/kard:${VERSION:-latest}
    ports:
      - "8000:80"
    working_dir: /app
    volumes:
      - .:/app

  redis:
    image: redis:7

  node:
    image: node:24-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./assets/react/:/app
    working_dir: /app/build
    command: sh -c "npm i && npm run watch"

  mercure:
    image: dunglas/mercure
    ports:
      - "8090:80"
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost:8000
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    volumes:
      - mercure_data:/data
      - mercure_config:/config

  mailer:
    image: axllent/mailpit
    ports:
      - "8025:8025"
  #
  # rabbitmq:
  #   image: rabbitmq:4-management-alpine
  #   ports:
  #     - "15672:15672"
  #
  # worker:
  #   build:
  #     context: .
  #     dockerfile: .devops/docker/Dockerfile
  #     target: ${BUILD_TARGET:-dev}
  #   image: ghcr.io/fan2shrek/kard:${VERSION:-latest}
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #   command: "php -d memory_limit=-1 bin/console messenger:consume async"

volumes:
  db_data:
  mercure_data:
  mercure_config:
