lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'

    api_platform:
        check_path: /api/login

    token_extractors:
        cookie:
            enabled: true
            name: auth_token

    set_cookies:
        auth_token: ~
