parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
      App\Game\Mode\GameModeInterface:
            tags: ['app.game_mode']

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Game/Mode/TraceableGameMode.php'
            - '../src/Kernel.php'

    App\Game\GameManager:
        arguments:
            $gameModes: !tagged_iterator app.game_mode

    App\Service\Redis\RedisConnection:
      arguments:
          - '@app.redis_provider'

    App\Service\AssetsProvider:
        arguments:
            $assetsPath: '%kernel.project_dir%/assets'

    app.redis_provider:
        class: \Redis
        factory: ['Symfony\Component\Cache\Adapter\RedisAdapter', 'createConnection']
        arguments:
            - '%env(string:REDIS_URL)%'
            - { retry_interval: 2, timeout: 10 }

    App\Service\StripeClient:
        arguments:
            $apiKey: '%env(STRIPE_API_KEY)%'
            $baseUrl: '%env(STRIPE_URL)%'

    App\Service\Bot\BotClient:
        arguments:
            $botServer: '%env(BOT_SERVER)%'
