name: Validate front Build

on:
  push:
    paths:
      - 'front/**'
  pull_request:
    paths:
      - 'front/**'

env:
  WITH_DOCKER: 0

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: front/package-lock.json

      - name: Install dependencies
        run: make npm-ci

      - name: Lint
        run: make js-lint-dry

      # TODO
      # - name: Build the app
      #   run: make front-build
