name: Code style

on:
  push:
  pull_request:

env:
  WITH_DOCKER: 0

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run php lint
        run: make php-lint-dry

      - name: Run twig lint
        run: make twig-lint-dry

      - name: Run phpstan
        run: make phpstan
