name: Update image 

on:
  push:
    branches:
      - main
      - develop

env:
  COMPOSE: docker compose
  REGISTRY: ghcr.io/fan2shrek/kard

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.sha }}${{ github.ref_name == 'develop' && '-dev' || '' }}
      VERSION_LATEST: latest
      BUILD_TARGET: prod
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.REGISTRY }}" | docker login ghcr.io -u Fan2Shrek --password-stdin

      - name: Build image
        run: BUILD_TARGET=prod ${COMPOSE} build php

      - name: Push image
        run: ${COMPOSE} push php

      - name: Tag image as latest
        if: github.ref == 'refs/heads/master'
        run: |
          docker tag ${REGISTRY}:${VERSION} ${REGISTRY}:${VERSION_LATEST}
          ${COMPOSE} push ${REGISTRY}:${VERSION_LATEST}

