name: Update image

on:
  push:
    branches:
      - master
      - develop

env:
  COMPOSE: docker compose
  REGISTRY: ghcr.io/fan2shrek/kard

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name == 'master' && 'latest' || 'dev' }}
      BUILD_TARGET: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.REGISTRY }}" | docker login ghcr.io -u Fan2Shrek --password-stdin

      - name: Build image
        run: BUILD_TARGET=prod ${COMPOSE} build php

      - name: Push image
        run: ${COMPOSE} push php
